# Project: wr80asm
# Makefile created by Dev-C++ 4.9.9.2

CPP  = g++.exe
CC   = gcc.exe
WINDRES = windres.exe
RES  = obj/wr80asm_private.res
OBJ  = obj/wr80asm.o $(RES)
LINKOBJ  = obj/wr80asm.o $(RES)
LIBS =  -L"C:/Dev-Cpp/lib" -static-libgcc  -fmessage-length=0 
INCS =  -I"C:/Dev-Cpp/include" 
CXXINCS =  -I"C:/Dev-Cpp/lib/gcc/mingw32/3.4.2/include"  -I"C:/Dev-Cpp/include/c++/3.4.2/backward"  -I"C:/Dev-Cpp/include/c++/3.4.2/mingw32"  -I"C:/Dev-Cpp/include/c++/3.4.2"  -I"C:/Dev-Cpp/include" 
BIN  = bin/wr80asm.exe
CXXFLAGS = $(CXXINCS)   -std=c99 -fmessage-length=0
CFLAGS = $(INCS)    -std=c99 -fmessage-length=0
RM = rm -f

.PHONY: all all-before all-after clean clean-custom

all: all-before bin/wr80asm.exe all-after


clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CC) $(LINKOBJ) -o "bin\wr80asm.exe" $(LIBS)

obj/wr80asm.o: src/wr80asm.c
	$(CC) -c src/wr80asm.c -o obj/wr80asm.o $(CFLAGS)

obj/wr80asm_private.res: wr80asm_private.rc 
	$(WINDRES) -i wr80asm_private.rc --input-format=rc -o obj/wr80asm_private.res -O coff 
